{% set name = "circuitq" %}
{% set version = "1.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f2461080859280c53c5b879fe0ce3ed804cd1a03a1d11727f623437ac4a1f65d

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}

  run:
    - networkx
    - numpy
    - python >={{ python_min }}
    - scipy
    - sympy

test:
  requires:
    - python {{ python_min }}
  imports:
    - circuitq

about:
  home: https://github.com/PhilippAumann/circuitq
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Automated design of superconducting qubits
  doc_url: https://circuitq.readthedocs.io/en/latest/
  dev_url: https://github.com/PhilippAumann/circuitq

extra:
  recipe-maintainers:
    - PhilippAumann
